use_frameworks!
platform :ios, '9.3'

target 'ShiftViewController_Example' do
  pod 'ShiftViewController', :path => '../'

  target 'ShiftViewController_Tests' do
    inherit! :search_paths

    
  end
end
